export const Constants = {
    public: {
        Enums: {
            balance_effect: ["positive", "negative", "neutral"],
            gender_type: ["m", "f", "d"],
            insured_person_status: ["active", "exited", "retired", "deceased"],
            marital_status_type: [
                "single",
                "married",
                "divorced",
                "widowed",
                "registered_partnership",
            ],
            mfa_event_type: [
                "setup_completed",
                "code_verified",
                "code_failed",
                "device_changed",
                "backup_code_used",
                "backup_codes_regenerated",
                "account_locked",
                "account_unlocked",
            ],
            pain001_version: ["pain.001.001.03.ch.02", "pain.001.001.09.ch.03"],
            payment_order_status: [
                "draft",
                "in_payment_run",
                "approved",
                "exported",
                "cancelled",
            ],
            payment_run_event_type: [
                "created",
                "order_added",
                "order_removed",
                "submitted",
                "visaed",
                "approved",
                "rejected",
                "exported",
                "renamed",
            ],
            payment_run_status: [
                "draft",
                "in_review",
                "visaed",
                "approved",
                "rejected",
                "exported",
            ],
            sort_direction: ["asc", "desc"],
            transaction_effect: ["credit", "debit"],
        },
    },
};
